name: unittest

on :
  push:
    branch:
    - main
  pull_request:
    branch:
    - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi

    - name: Unittest with Nose
      run: |
        nosetests 

  
    